_target_: hydra_plugins.hydra_submitit_launcher.submitit_launcher.SlurmLauncher
timeout_min: 1440
cpus_per_task: 4
gpus_per_node: 1
tasks_per_node: 1
mem_gb: 64
nodes: 1
partition: gpu
name: ${hydra.job.name}
comment: "SART experiment via hydra-submitit-launcher"
